//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Trade_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Traders = new HashSet<Trader>();
        }
    
        public int Customer_id { get; set; }
        public string Customer_user_name { get; set; }
        public string Customer_name { get; set; }
        public string Customer_password { get; set; }
        public string Customer_mail { get; set; }
        public string Customer_tel { get; set; }
        public string Customer_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trader> Traders { get; set; }
    }
}
