//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Trade_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_id { get; set; }
        public int Trader_id { get; set; }
        public int Stock_id { get; set; }
        public double Transaction_value { get; set; }
        public int Stock_quantity { get; set; }
        public string Transaction_Type { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Trader Trader { get; set; }
    }
}
